#!/usr/bin/env bash

declare -a homes=(
"$HOME/git/$PROJECT/todo.md"
"$HOME/git/mono/$PROJECT/todo.md"
"$HOME/git/personal/projects/$PROJECT/todo.md"
"$HOME/git/personal/projects/${PROJECT}.md"
)

org-help() {
  echo "org-find $PROJECT for a specific project"
  echo "org-show for all projects"
}


org-find() {
  #  finds a single project todo.txt
  PROJECT=$1

  WROTEFILE="false"
  for FILENAME in "${homes[@]}"
    do
    if [[ ! -f "$FILENAME" ]]; then
      :  # pass
    else
      echo $FILENAME
      break
  fi
  done
}

org-show() {
  #  look for all todo.md files in home
  echo "finding project todo.md's ..."
  PROJECTS=$(find /Users/adam/git -name "todo.md" | awk -F "/" '{print $(NF-1)}' | sort)
  echo " "
  echo "Projects"
  echo "-----"
  echo "$PROJECTS" | tr " " "\n"
}
